# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ど〜なっつ、時を司るプログラミング言語
email: your-email@domain.com
description: ど〜なっつは、処理系の時間を巻き戻す機能をもつプログラミング言語です。 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://donut-lang.github.io" # the base hostname & protocol for your site
twitter_username: tikal
github_username:  ledyba

# Build settings
markdown: kramdown
